# Generated by Django 3.2.3 on 2022-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniqe_name_owner'),
        ),
    ]
